# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenMinutesApp', '0003_auto_20161020_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='belong_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='under_comments', to='tenMinutesApp.Article'),
        ),
    ]
