# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenMinutesApp', '0005_comment_best_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='editors_choice',
            field=models.BooleanField(default=False),
        ),
    ]
